In [2]:
import numpy as np
import pandas as pd

In [8]:
products = pd.read_csv('wc-product-export-22-11-2023-1700682750584.csv')

In [9]:
products

,ID,Type,SKU,Name,Published,Is featured?,Visibility in catalogue,Short description,Description,Date sale price starts,...,Attribute 3 visible,Attribute 3 global,Attribute 4 name,Attribute 4 value(s),Attribute 4 visible,Attribute 4 global,Attribute 5 name,Attribute 5 value(s),Attribute 5 visible,Attribute 5 global
0,305,variable,NaN,Sabba Orthopaedic Mattress,1,0,visible,NaN,"<div class=""KVL47"">\r\n<div class=""XP2Bud"">\r\...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,450,variation,NaN,Sabba Orthopaedic Mattress - Single,1,0,visible,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,451,variation,NaN,Sabba Orthopaedic Mattress - Double,1,0,visible,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,455,variable,NaN,Oxford Mattress,1,0,visible,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,459,variation,NaN,Oxford Mattress - Single,1,0,visible,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,4122,simple,NaN,Verona 3 Seater Sofabed,1,0,visible,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,4124,simple,NaN,Balmour 3 Seater Sofabed,1,0,visible,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,4126,simple,NaN,Windsor Sofabed,1,0,visible,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
599,4128,simple,NaN,Jamie 2 Seater Grey,1,0,visible,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600,4130,simple,NaN,Jamie 2 Seater Orange Tan,1,0,visible,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
import pymongo
import json

data_to_insert = products.to_dict(orient='records')

client = pymongo.MongoClient("mongodb+srv://wasimibkhan:09uG5h4iqGYSOnpi@cluster0.txfwy7a.mongodb.net/?retryWrites=true&w=majority")
db = client["sabba-furniture"]
collection = db.products  

collection.insert_many(data_to_insert)

client.close()

NameError: name 'furniture' is not defined